name: Tests

on: [push]

jobs:
  test-elixir-latest:
    name: Elixir 1.10

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install sodium
      run: sudo apt-get update && sudo apt-get install libsodium23 libsodium-dev -y

    - uses: actions/setup-elixir@v1
      with:
        otp-version: 22.x
        elixir-version: 1.10.x

    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Test code
      run: mix test